// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZHz8563KwvaI14SLALxfjhbr0r_aUAw',
    appId: '1:373465825448:web:33fd3afb8ef64f3f3bc29d',
    messagingSenderId: '373465825448',
    projectId: 'mobile-store-76bc4',
    authDomain: 'mobile-store-76bc4.firebaseapp.com',
    storageBucket: 'mobile-store-76bc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFtaoPpDZ4Z1a8ru7zXTn7WLgxqjnU87c',
    appId: '1:373465825448:android:06ec66e7389f88163bc29d',
    messagingSenderId: '373465825448',
    projectId: 'mobile-store-76bc4',
    storageBucket: 'mobile-store-76bc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHP6wHEpK31P4BlYpGl6dBnYEceDe-j4A',
    appId: '1:373465825448:ios:035b577c53d289853bc29d',
    messagingSenderId: '373465825448',
    projectId: 'mobile-store-76bc4',
    storageBucket: 'mobile-store-76bc4.appspot.com',
    iosClientId: '373465825448-n7a8p8ivcqae0e9dbk51hlkrtdavascq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneStoreApp',
  );
}
